/**
 * This is a replacement for the declarations generated by dfx.
 * These work properly with `ng serve` in dev mode.
 */

import { isDevMode } from "@angular/core";
import { Actor, ActorSubclass, HttpAgent, HttpAgentOptions } from "@dfinity/agent";
import type { IDL } from '@dfinity/candid';

import * as backend_declarations from "declarations/ic-ipfs-backend/ic-ipfs-backend.did.js";

// TODO: Inject this with webpack instead
// @ts-ignore
globalThis.process = { env: {
  DFX_NETWORK: 'local',
  CANISTER_ID_IC_IPFS_FRONTEND: 'u6s2n-gx777-77774-qaaba-cai',
  CANISTER_ID_IC_IPFS_BACKEND: 'uxrrr-q7777-77774-qaaaq-cai',
  CANISTER_ID: 'u6s2n-gx777-77774-qaaba-cai',
}};

// TODO: Set process.env with custom webpack. Currently hacked into index.html
// TODO: Use injection tokens to be more angular like.
export const BACKEND_CANISTER_ID = (process as any).env.CANISTER_ID_IC_IPFS_BACKEND;
export type BACKEND_SERVICE = backend_declarations._SERVICE;
export const BACKEND = createActor<BACKEND_SERVICE>(
  BACKEND_CANISTER_ID,
  backend_declarations.idlFactory
);

function createActor<T>(canisterId: string, idlFactory: IDL.InterfaceFactory): ActorSubclass<T> {
  const options: HttpAgentOptions = {};
  if (isDevMode()) {
    options.host = 'http://localhost:4943';
  }
  if ((process as any).env.DFX_NETWORK !== "ic") {
    options.shouldFetchRootKey = true;
  }

  // TODO: Should we be using the async version here? Ideally the actor
  // methods would just wait for the agent to be ready.
  const agent = HttpAgent.createSync(options);
  return Actor.createActor(idlFactory, {
    agent,
    canisterId
  });
};
